config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
      resources :reviews, only: [ :index, :new, :create ]
    end
    resources :reviews, only: [ :show, :edit ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, :address, presence: true
  validates :category, presence: true, inclusion: { in: %w(chinese italian japanese french belgian) }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true }, inclusion: { in: [0, 1, 2, 3, 4, 5] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
    redirect_to restaurant_path(@restaurant.id)
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update(params)
      redirect_to restaurant_path(@restaurant)
    else
      render :edit
    end

    redirect_to restaurant_path(@restaurant.id)
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy

    redirect_to restaurants_path
  end

  private

  def restaurant_params
    return params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @restaurant = Restaurant.find(params[:restaurant_id])
    @reviews = @restaurant.reviews
  end

  def show
    # @restaurant = Restaurant.find(params[:id])
    # @review = @restaurant.review
    @review = Review.find(params[:id])
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])

    @review = Review.new(review_params)
    @review.restaurant = @restaurant

    if @review.save
      redirect_to restaurants_path(@restaurant.id)
    else
      render :new
    end
  end

  def review_params
    return params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <!-- app/views/layouts/application.html.erb -->
  <head>
    <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <!-- [...] -->
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/restaurants/_form.html.erb
<!-- app/views/restaurants/_form.html.erb -->
<%= simple_form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @restaurant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category %>
  </div>
  <div class="form-actions">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<%= link_to "Add restaurant", new_restaurant_path, class: "btn btn-primary"%></li>
<ul>
  <% @restaurants.each do |restaurant| %>
  <li>Name: <%= restaurant.name %></li>
  <li>Address: <%= restaurant.address %></li>
  <li>Phone number: <%= restaurant.phone_number %></li>
  <li>Type: <%= restaurant.category %></li>

  <li><%= link_to "See details", restaurant_path(restaurant.id), class: "btn btn-primary"%></li>
  <br>
   <li> <%= link_to "See reviews", restaurant_reviews_path(restaurant.id), class: "btn btn-primary" %></li>
  <br>
  <% end %>

</ul>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<h1> Restaurants </h1>
<ul>
  <h2> <%= @restaurant.name %> </h2>
  <li> <%= @restaurant.address %></li>
  <li> <%= @restaurant.phone_number %></li>
  <li> <%= @restaurant.category %></li>
  <%= link_to "Edit restaurant", edit_restaurant_path(@restaurant.id), class: "btn btn-primary mb-2" %>
  <%= link_to "Delete restaurant", restaurant_path(@restaurant.id), method: :destroy, data: { confirm: "Are you sure you want to delete?" }, class: "btn btn-primary mb-2" %>
  <br>
  <%= link_to "View next", restaurant_path(@restaurant.id+1), class: "btn btn-primary mb-2" %>
  <%= link_to "View previous", restaurant_path(@restaurant.id-1), class: "btn btn-primary mb-2" %>
  <%= link_to "View all", restaurants_path, class: "btn btn-primary mb-2" %>
<h2> Reviews </h2>
  <% @restaurant.reviews.each do |review| %>
  <ul>
    <li> <%= review.content %> </li>
    <li> <%= review.rating %></li>
    <% if review.content.nil? %>
      <%= "No reviews to show" %>
    <% end %>
  </ul>
  <% end %>
  <%= link_to "Add review", new_restaurant_review_path(@restaurant.id), method: :new, class: "btn btn-primary"%>
  <%= link_to "Go back", restaurants_path, class: "btn btn-primary"%>
</ul>

app/views/reviews/_form.html.erb
<!-- app/views/restaurants/_form.html.erb -->
<%= simple_form_for [@restaurant, @review] do |f| %>
  <% if @review.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :content %>
  <%= f.input :rating %>

  <%= f.submit "add a review", class: "btn btn-primary" %>

<% end %>

app/views/reviews/edit.html.erb
<h1> Edit review </h1>
<%= render "form" %>

app/views/reviews/index.html.erb
<h1> Reviews </h1>
<% @reviews.each do |review| %>
<ul>
  <li> <%= review.content %> </li>
  <li> <%= review.rating %></li>
</ul>
<% end %>


<%= link_to "Add review", new_restaurant_review_path(@restaurant.id), method: :new, class: "btn btn-primary"%></li>

<%= link_to "Go back", restaurants_path, class: "btn btn-primary"%></li>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form', restaurant: @restaurant, review: @review %>
<%= link_to 'Back', restaurant_reviews_path %>

app/views/reviews/show.html.erb
 <h1> Review </h1>
<ul>
  <li> <%= @review.content %> </li>
  <li> <%= @review.rating %></li>
</ul>